# Generated by Django 4.0.6 on 2022-08-02 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0004_alter_avaliacao_nota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='user',
            new_name='usuario',
        ),
    ]
