# Generated by Django 4.0.6 on 2022-08-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descrcao', models.TextField()),
                ('horario_funcionamento', models.TextField()),
                ('indade_minima', models.IntegerField()),
            ],
        ),
    ]
