# Generated by Django 4.0.6 on 2022-08-02 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atracao',
            old_name='descrcao',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='atracao',
            old_name='indade_minima',
            new_name='idade_minima',
        ),
    ]
